global:
  scrape_interval: 1s
alerting:
  alertmanagers:
    - static_configs:
        - targets:
rule_files:

scrape_configs:
  - job_name: 'bar'
    static_configs:
      - targets: ['127.0.0.1:9123']
