{
 "title": "BAR",
 "time": { "from": "now-3m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "gameID",
    "label": "Game ID",
    "query": {
     "query": "label_values(game_info, gameID)"
    }
   },
   {
    "name": "players",
    "label": "Players",
    "query": {
     "query": "label_values(resource_total{gameID=\"$gameID\"},team)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Damage dealt",
   "type": "stat",
   "description": "The amount of damage the top 3 players have dealt in the entire game up until now.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(3, resource_total{resource=\"damage\",stat=\"dealt\",gameID=\"$gameID\",team=~\"$players\"})",
     "legendFormat": "{{team}}"
    }
   ]
  },
  {
   "title": "Damage received",
   "type": "stat",
   "description": "The amount of damage the top 3 players have received in the entire game up until now.",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(3, resource_total{resource=\"damage\",stat=\"received\",gameID=\"$gameID\",team=~\"$players\"})",
     "legendFormat": "{{team}}"
    }
   ]
  },
  {
   "title": "Units produced",
   "type": "stat",
   "description": "The amount of units and buildings the top 3 players have produced in the entire game up until now.",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(3, resource_total{resource=\"units\",stat=\"produced\",gameID=\"$gameID\",team=~\"$players\"})",
     "legendFormat": "{{team}}"
    }
   ]
  },
  {
   "title": "Units killed",
   "type": "stat",
   "description": "The amount of units and buildings the top 3 players have killed in the entire game up until now.",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(3, resource_total{resource=\"units\",stat=\"killed\",gameID=\"$gameID\",team=~\"$players\"})",
     "legendFormat": "{{team}}"
    }
   ]
  },
  {
   "title": "Construction Turrets",
   "type": "stat",
   "description": "The amount of construction turrets the top 3 players have right now.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(3, units{name=\"constructionturret\",gameID=\"$gameID\",team=~\"$players\"})",
     "legendFormat": "{{team}}"
    }
   ]
  },
  {
   "title": "E-Conv Energy Need",
   "type": "stat",
   "description": "The amount of energy the top 3 players need to fully run all their energy converters right now.",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(3, units{name=\"econvs\",stat=\"energy\",gameID=\"$gameID\",team=~\"$players\"})",
     "legendFormat": "{{team}}"
    }
   ]
  },
  {
   "title": "Buildspeed",
   "type": "stat",
   "description": "The sum of all the building and unit buildspeeds for the top 3 players (including units that have buildspeed but cannot actually build units by themselves, like rezzers or construction turrets).",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(3, units{resource=\"buildspeed\",gameID=\"$gameID\",team=~\"$players\"})",
     "legendFormat": "{{team}}"
    }
   ]
  },
  {
   "title": "Factories",
   "type": "stat",
   "description": "The number of factories the top 3 players have.",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(3, units{resource=\"building\",gameID=\"$gameID\",type=\"factory\",team=~\"$players\"})",
     "legendFormat": "{{team}}"
    }
   ]
  },
  {
   "title": "Metal Combat Static",
   "type": "stat",
   "description": "The amount of metal the top 3 players have in static (i.e. non-mobile) units and buildings from the Combat category (almost anything with a weapon).",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(3, units{category=\"Combat\",stat=\"metal\", mobility=\"static\", gameID=\"$gameID\",team=~\"$players\"})",
     "legendFormat": "{{team}}"
    }
   ]
  },
  {
   "title": "Metal Combat Mobile",
   "type": "stat",
   "description": "The amount of metal the top 3 players have in mobile (i.e. can move around on its own) units from the Combat category (almost anything with a weapon).",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(3, units{category=\"Combat\",stat=\"energy\", mobility=\"mobile\", gameID=\"$gameID\",team=~\"$players\"})",
     "legendFormat": "{{team}}"
    }
   ]
  },
  {
   "title": "Metal Economy",
   "type": "stat",
   "description": "The amount of metal the top 3 players have in Economy buildings and units.",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(3, sum(units{category=\"Economy\",stat=\"metal\",gameID=\"$gameID\",team=~\"$players\"}) by (team))",
     "legendFormat": "{{team}}"
    }
   ]
  },
  {
   "title": "Metal Production",
   "type": "stat",
   "description": "The amount of metal the top 3 players have in Production buildings.",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(3, sum (units{category=\"Production\",stat=\"metal\",gameID=\"$gameID\",team=~\"$players\"}) by (team))",
     "legendFormat": "{{team}}"
    }
   ]
  },
  {
   "title": "Metal Utility Static",
   "type": "stat",
   "description": "The amount of metal for the top 3 players that they have in Utility static (i.e. non-mobile) units and buildings (e.g. Radar, Jammer, ...)",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(3, units{category=\"Utility\",stat=\"metal\",mobility=\"static\", gameID=\"$gameID\",team=~\"$players\"})",
     "legendFormat": "{{team}}"
    }
   ]
  },
  {
   "title": "Metal Utility Mobile",
   "type": "stat",
   "description": "The amount of metal for the top 3 players that they have in Utility mobile (i.e. can move on their own) units (e.g. Radar, Jammer, ...)",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(3, units{category=\"Utility\",stat=\"metal\", mobility=\"mobile\",gameID=\"$gameID\",team=~\"$players\"})",
     "legendFormat": "{{team}}"
    }
   ]
  },
  {
   "title": "Wind Strength",
   "type": "stat",
   "description": "The current wind strength.",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "wind_strength{gameID=\"$gameID\"}",
     "legendFormat": "wind {{min}} - {{max}}"
    }
   ]
  },
  {
   "title": "Tidal Strength",
   "type": "stat",
   "description": "The tidal strength, fixed for a map, does not vary.",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tidal_strength{gameID=\"$gameID\"}"
    }
   ]
  },
  {
   "title": "Metal produced",
   "type": "stat",
   "description": "The total amount of metal produced by each Team up until now.",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(resource_total{resource=\"metal\",stat=\"produced\",gameID=\"$gameID\"}) by (allyTeam)",
     "legendFormat": "{{allyTeam}}"
    }
   ]
  },
  {
   "title": "Energy produced",
   "type": "stat",
   "description": "The total amount of energy produced by each Team up until now.",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(resource_total{resource=\"energy\",stat=\"produced\",gameID=\"$gameID\"}) by (allyTeam)",
     "legendFormat": "{{allyTeam}}"
    }
   ]
  },
  {
   "title": "Energy Expense",
   "type": "timeseries",
   "description": "Current energy expense.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "resource{stat=\"expense\",resource=\"energy\",gameID=\"$gameID\",team=~\"$players\"}",
     "legendFormat": "{{team}}"
    }
   ]
  },
  {
   "title": "Metal Expense",
   "type": "timeseries",
   "description": "Current metal expense.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "resource{stat=\"expense\",resource=\"metal\",gameID=\"$gameID\",team=~\"$players\"}",
     "legendFormat": "{{team}}"
    }
   ]
  },
  {
   "title": "Energy Income",
   "type": "timeseries",
   "description": "Current energy income.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "resource{stat=\"income\",resource=\"energy\",gameID=\"$gameID\",team=~\"$players\"}",
     "legendFormat": "{{team}}"
    }
   ]
  },
  {
   "title": "Metal Income",
   "type": "timeseries",
   "description": "Current metal income.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "resource{stat=\"income\",resource=\"metal\",gameID=\"$gameID\",team=~\"$players\"}",
     "legendFormat": "{{team}}"
    }
   ]
  },
  {
   "title": "Damage dealt",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "resource_total{resource=\"damage\",stat=\"dealt\",gameID=\"$gameID\",team=~\"$players\"}",
     "legendFormat": "{{team}}"
    }
   ]
  },
  {
   "title": "Damage received",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "resource_total{resource=\"damage\",stat=\"received\",gameID=\"$gameID\",team=~\"$players\"}",
     "legendFormat": "{{team}}"
    }
   ]
  },
  {
   "title": "Units killed",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "unit_stats{type=\"killed\",gameID=\"$gameID\",team=~\"$players\"}",
     "legendFormat": "{{team}}"
    }
   ]
  },
  {
   "title": "Units died",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 38 },
   "targets": [
    {
     "expr": "unit_stats{type=\"died\",gameID=\"$gameID\",team=~\"$players\"}",
     "legendFormat": "{{team}}"
    }
   ]
  }
 ]
}